Fix SyntaxError: Illegal return statement
inspect-js/is-map pull request #4
Opened 2019-12-16 10:32 UTC by gitim

Faced with SyntaxError in this package, because some package in my project depend from this package.

2019-12-16 15:43 UTC, ljharb requested changes
See https://github.com/inspect-js/is-set/pull/4#pullrequestreview-332658947

This is not a syntax error whatsoever; this is a node module and top level return is allowed in it.

What bundler are you using that breaks on valid node modules?

2019-12-16 15:43 UTC, ljharb commented
https://github.com/inspect-js/is-set/pull/4#pullrequestreview-332658947

2019-12-17 09:29 UTC, Jessidhia requested changes

2019-12-17 09:29 UTC, Jessidhia commented on index.js
> -	return;
Even if you were to get rid of these `return`s, this is not it; you need to convert the rest of the file into `else` bodies.

2019-12-17 20:55 UTC, merged